#!/bin/sh
#
# Writes the final sources.list file
#

CHROOT=$(mount | grep proc | grep calamares | awk '{print $3}' | sed -e "s#/proc##g")
#RELEASE="verbeek"

cp /etc/apt/sources.list $CHROOT/etc/apt/sources.list

exit 0
